name: CloudGuard Code Security

on: workflow_call

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
          
  spectral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CloudGuard Code Security Scan
        uses: checkpointsw/spectral-github-action@v4
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --fail-on-error --engines secrets,iac,oss --asset-mapping github.${{ github.repository_owner }}
