name: Code Analysis

on: workflow_call

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
          
  spectral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral Scan
        uses: SpectralOps/spectral-github-action@v2
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --fail-on-error --engines secrets,iac,oss --asset-mapping github.${{ github.repository_owner }}
